# Generated by Django 4.2.8 on 2023-12-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_filter', '0002_product_type_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
